name: Build Qt Project

on:
  push:
    branches: [ main ]
    paths-ignore: ['**']
    tags: ['v*']
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-commit:
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ steps.check.outputs.should-run }}
    steps:
      - uses: actions/checkout@v4
      - id: check
        run: |
          if echo "${{ github.event.head_commit.message }}" | grep -iE "\[build\]|\[release\]"; then
            echo "should-run=true" >> $GITHUB_OUTPUT
          else
            echo "should-run=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check-commit
    if: |
      needs.check-commit.outputs.should-run == 'true' ||
      github.event_name == 'workflow_dispatch' ||
      startsWith(github.ref, 'refs/tags/v')
    
    strategy:
      fail-fast: false  # Продолжать сборку для других ОС при ошибке
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            qt_version: '6.8.0'
            qt_arch: gcc_64
            qt_dir: ${{ github.workspace }}/Qt
          - os: windows-latest
            qt_version: '6.8.0'
            qt_arch: win64_msvc2019_64
            qt_dir: ${{ github.workspace }}/Qt
          - os: macos-latest
            qt_version: '6.8.0'
            qt_arch: clang_64
            qt_dir: ${{ github.workspace }}/Qt

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    # Установка зависимостей для Linux
    - name: Install Linux Dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgl1-mesa-dev libxkbcommon-x11-0 libpulse-dev

    # Установка Qt с использованием aqtinstall
    - name: Install Qt
      run: |
        python -m pip install aqtinstall
        python -m aqt install-qt -O ${{ matrix.qt_dir }} linux desktop ${{ matrix.qt_version }} gcc_64 -m qtdeclarative qtquickcontrols2
      if: matrix.os == 'ubuntu-latest'

    - name: Install Qt (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        python -m pip install aqtinstall
        python -m aqt install-qt -O ${{ matrix.qt_dir }} windows desktop ${{ matrix.qt_version }} win64_msvc2019_64 -m qtdeclarative qtquickcontrols2

    - name: Install Qt (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        python -m pip install aqtinstall
        python -m aqt install-qt -O ${{ matrix.qt_dir }} mac desktop ${{ matrix.qt_version }} clang_64 -m qtdeclarative qtquickcontrols2

    # Вывод отладочной информации
    - name: Debug Qt Installation
      run: |
        echo "Qt installation directory contents:"
        ls -R ${{ matrix.qt_dir }}
      shell: bash

    - name: Create Build Directory
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake (Windows)
      if: matrix.os == 'windows-latest'
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: |
        export Qt6_DIR="${{ matrix.qt_dir }}/${{ matrix.qt_version }}/${{ matrix.qt_arch }}/lib/cmake/Qt6"
        cmake .. -DCMAKE_BUILD_TYPE=Release -A x64 -DCMAKE_PREFIX_PATH="${{ matrix.qt_dir }}/${{ matrix.qt_version }}/${{ matrix.qt_arch }}"

    - name: Configure CMake (Unix)
      if: matrix.os != 'windows-latest'
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: |
        export Qt6_DIR="${{ matrix.qt_dir }}/${{ matrix.qt_version }}/${{ matrix.qt_arch }}/lib/cmake/Qt6"
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="${{ matrix.qt_dir }}/${{ matrix.qt_version }}/${{ matrix.qt_arch }}"

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config Release

    - name: Package (Windows)
      if: matrix.os == 'windows-latest'
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: |
        ${{ matrix.qt_dir }}/${{ matrix.qt_version }}/${{ matrix.qt_arch }}/bin/windeployqt.exe Release/*.exe --qmldir ../src/QML

    - name: Package (MacOS)
      if: matrix.os == 'macos-latest'
      working-directory: ${{github.workspace}}/build
      run: |
        ${{ matrix.qt_dir }}/${{ matrix.qt_version }}/${{ matrix.qt_arch }}/bin/macdeployqt *.app -qmldir=../src/QML -dmg

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-build
        path: |
          ${{github.workspace}}/build/**/*.exe
          ${{github.workspace}}/build/**/*.app
          ${{github.workspace}}/build/**/*.dmg
          ${{github.workspace}}/build/**/*.so
          ${{github.workspace}}/build/**/*.dll