name: Build iOS

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    env:
      QT_DIR: ${{ github.workspace }}/Qt
      BUILD_TYPE: Release
      APP_NAME: appTestBinance

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Python and aqtinstall
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install aqtinstall
      run: |
        python -m pip install --upgrade pip
        python -m pip install aqtinstall

    - name: Cache Qt
      uses: actions/cache@v3
      with:
        path: ${{ env.QT_DIR }}
        key: ${{ runner.os }}-qt-6.8.0-${{ hashFiles('**/CMakeLists.txt') }}

    - name: Install Qt (All)
      shell: bash
      run: |
        mkdir -p "${{ env.QT_DIR }}"
        python -m aqt install-qt \
          --outputdir "${{ env.QT_DIR }}" \
          mac desktop \
          6.8.0 \
          -m all

    - name: Install Qt for iOS
      run: |
        mkdir -p "${{ env.QT_DIR }}"
        python -m aqt install-qt \
          --outputdir "${{ env.QT_DIR }}" \
          mac ios \
          6.8.0 \
          ios \
          -m all

    - name: Check CMake Version
      run: cmake --version

    - name: Create Build Directory
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake for iOS
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: |
        export Qt6_DIR="${{ env.QT_DIR }}/6.8.0/ios/lib/cmake/Qt6"
        cmake .. \
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
          -DCMAKE_PREFIX_PATH="${{ env.QT_DIR }}/6.8.0/ios" \
          -DCMAKE_TOOLCHAIN_FILE="${{ env.QT_DIR }}/6.8.0/ios/lib/cmake/Qt6/qt.toolchain.cmake" \
          -DQT_BUILD_IOS=True \
          -DQT_HOST_PATH="${{ env.QT_DIR }}/6.8.0/macos" \
          -DPLATFORM=OS64 \
          -DENABLE_BITCODE=FALSE \
          -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED=NO \
          -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED=NO

    - name: Build iOS Bundle
      working-directory: ${{github.workspace}}/build
      shell: bash
      timeout-minutes: 30
      run: cmake --build . --config ${{ env.BUILD_TYPE }} --parallel $(sysctl -n hw.logicalcpu)

    - name: Debug Build Directory
      working-directory: ${{github.workspace}}/build
      run: |
        echo "Build directory contents:"
        ls -la

    - name: Package iOS App
      working-directory: ${{github.workspace}}/build
      run: |
        APP_PATH=$(find . -name "${{ env.APP_NAME }}.app" -type d)
        if [ -z "$APP_PATH" ]; then
          echo "Error: .app bundle not found"
          exit 1
        fi
        "${{ env.QT_DIR }}/6.8.0/ios/bin/macdeployqt" "$APP_PATH" \
          -verbose=2 -qmlimport=${{ github.workspace }}/QML

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.APP_NAME }}-ios
        path: ${{github.workspace}}/build/**/${{ env.APP_NAME }}.app/