name: Build for IOS 

on:
  workflow_dispatch:

jobs:  
  ios-build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.8.0'
        host: 'mac'
        target: 'ios'
        install-deps: 'true'
        modules: 'qtwebsockets qtconnectivity'
        cache: 'false'
        cache-key-prefix: 'install-qt-action'
        setup-python: 'false'
    
    - name: Configure CMake
      run: |
        cmake -B build \
        -DIOS=ON \
        -DCMAKE_BUILD_TYPE=Release
        
    - name: Build
      run: cmake --build build --config Release
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-app-bundle
        path: build/appTestBinance.app