name: Build for IOS 

on:
  workflow_dispatch:

jobs:  
  ios-build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel py7zr==0.20.* --break-system-packages

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.8.0'
        host: 'mac'
        target: 'ios'
        modules: 'qtwebsockets qtconnectivity'
    
    - name: Configure CMake
      run: |
        echo "Qt6_DIR path: $Qt6_DIR"
        cmake -B build \
        -DIOS=ON \
        -DCMAKE_BUILD_TYPE=Release \
        -DQt6_DIR="/Users/runner/work/biManager/Qt/6.8.0/ios/lib/cmake/Qt6" \
        -DQt6_ANDROID_ABIS=arm64-v8a \
        -DCMAKE_PREFIX_PATH="/Users/runner/work/biManager/Qt/6.8.0/ios" \
        -DCMAKE_TOOLCHAIN_FILE="/Users/runner/work/biManager/Qt/6.8.0/ios/lib/cmake/Qt6/qt.toolchain.cmake"
        
    - name: Build
      run: cmake --build build --config Release
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-app-bundle
        path: build/appTestBinance.app