name: Build iOS

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    env:
      QT_DIR: ${{ github.workspace }}/Qt
      BUILD_TYPE: Release
      APP_NAME: appTestBinance

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Python and aqtinstall
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
      run: |
        python -m pip install --upgrade pip
        python -m pip install aqtinstall

    - name: Install Qt for iOS
      run: |
        mkdir -p "${{ env.QT_DIR }}"
        python -m aqt install-qt \
          --outputdir "${{ env.QT_DIR }}" \
          mac ios \
          6.8.0 \
          ios \
          -m qtbase,qtquickcontrols2,qtwebsockets,qtsql,qtnetwork

    - name: Create Build Directory
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake for iOS
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: |
        export Qt6_DIR="${{ env.QT_DIR }}/6.8.0/ios/lib/cmake/Qt6"
        cmake .. \
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
          -DCMAKE_PREFIX_PATH="${{ env.QT_DIR }}/6.8.0/ios" \
          -DCMAKE_TOOLCHAIN_FILE="${{ env.QT_DIR }}/6.8.0/ios/lib/cmake/Qt6/qt.toolchain.cmake" \
          -DQT_BUILD_IOS=True

    - name: Build iOS Bundle
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{ env.BUILD_TYPE }} --parallel $(sysctl -n hw.logicalcpu)

    - name: Debug Build Directory
      working-directory: ${{github.workspace}}/build
      run: |
        echo "Build directory contents:"
        ls -la

    - name: Package iOS App
      working-directory: ${{github.workspace}}/build
      run: |
        mkdir -p ${{ env.APP_NAME }}.app
        "${{ env.QT_DIR }}/6.8.0/ios/bin/macdeployqt" ${{ env.APP_NAME }}.app \
          -verbose=2 -qmlimport=${{ github.workspace }}/QML

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.APP_NAME }}-ios
        path: |
          ${{ env.APP_NAME }}.app
